- name: Evaluate insecure example (expected to fail)
        run: |
          echo "Running OPA on insecure-s3..."
          opa eval --input terraform-examples/insecure-s3/main.tf --data policies --format pretty "data.nist" || true
